apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice
  description: Сервис в Backstage
  annotations:
      backstage.io/techdocs-ref: value
spec:
  type: service
  lifecycle: experimental
  owner: guests
